Repository discord-jar/discord.jar, pull requests merged in 2023-01, with the labels that each got.

#84 [BUG FIX] Fixed options & subcommands being shared between commands.
  examples/ExampleCommand.java
  src/main/java/com/seailz/discordjv/DiscordJv.java
  src/main/java/com/seailz/discordjv/command/listeners/slash/SlashCommandListener.java
Labels: type: bug, priority: high, status: completed, IMPORTANT, type: examples

#86 [CACHE] Added new `JsonCache` object and added caching to getSelfInfo
  src/main/java/com/seailz/discordjv/DiscordJv.java
  src/main/java/com/seailz/discordjv/gateway/GatewayFactory.java
  src/main/java/com/seailz/discordjv/model/guild/Guild.java
  src/main/java/com/seailz/discordjv/model/guild/Member.java
  src/main/java/com/seailz/discordjv/utils/cache/JsonCache.java
  src/main/java/com/seailz/discordjv/utils/cache/impl/JsonCacheImpl.java
  src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java
Labels: type: feature, priority: low, status: completed

#88 Support Image URLs
  src/main/java/com/seailz/discordjv/model/guild/Guild.java
  src/main/java/com/seailz/discordjv/model/user/User.java
  src/main/java/com/seailz/discordjv/utils/CDNAble.java
  src/main/java/com/seailz/discordjv/utils/StringFormatter.java
Labels: type: feature, priority: medium, status: completed

#89 Formatted Message Content
  src/main/java/com/seailz/discordjv/model/message/Message.java
Labels: type: feature, priority: low, status: completed

#90 Channel Transcripts
  pom.xml
  src/main/java/com/seailz/discordjv/model/channel/MessagingChannel.java
  src/main/java/com/seailz/discordjv/model/channel/transcript/TranscriptFormatter.java
  src/main/java/com/seailz/discordjv/model/message/Message.java
  src/main/java/com/seailz/discordjv/utils/URLS.java
  src/main/resources/template.html
Labels: type: feature, priority: low, status: completed

#91 File Uploads
  src/main/java/com/seailz/discordjv/action/MessageCreateAction.java
  src/main/java/com/seailz/discordjv/model/channel/MessagingChannel.java
  src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java
Labels: type: feature, priority: medium, status: completed

#97 [FEATURE] HTTP-Only Support
  README.md
  pom.xml
  src/main/java/com/seailz/discordjv/DiscordJv.java
  src/main/java/com/seailz/discordjv/command/CommandDispatcher.java
  src/main/java/com/seailz/discordjv/http/HttpOnlyApplication.java
  src/main/java/com/seailz/discordjv/http/HttpOnlyManager.java
  src/main/java/com/seailz/discordjv/http/SecurityManager.java
  src/main/java/com/seailz/discordjv/model/interaction/Interaction.java
  src/main/java/com/seailz/discordjv/utils/HTTPOnlyInfo.java
Labels: type: feature, priority: high, status: completed, LARGE, IMPORTANT, type: doc

#99 [FIX] Uploading Files
  src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java
Labels: type: bug, priority: medium, status: completed

#100 [FEATURE] Added some extra interaction methods
  src/main/java/com/seailz/discordjv/events/model/interaction/InteractionEvent.java
  src/main/java/com/seailz/discordjv/model/interaction/callback/InteractionHandler.java
Labels: type: feature, priority: medium, status: completed

#101 [FEATURE] Interaction Messages Editing
  src/main/java/com/seailz/discordjv/action/interaction/EditInteractionMessageAction.java
  src/main/java/com/seailz/discordjv/model/interaction/callback/InteractionHandler.java
  src/main/java/com/seailz/discordjv/model/interaction/callback/internal/InteractionHandlerImpl.java
  src/main/java/com/seailz/discordjv/utils/URLS.java
Labels: type: feature, priority: medium, status: completed

#103 [FEATURE] Type 6 interaction response
  src/main/java/com/seailz/discordjv/model/interaction/callback/InteractionHandler.java
  src/main/java/com/seailz/discordjv/model/interaction/callback/internal/InteractionHandlerImpl.java
Labels: type: feature, priority: low, status: completed

#106 [FEATURE] Added support for retrieval of guild members through the gateway
  src/main/java/com/seailz/discordjv/DiscordJv.java
  src/main/java/com/seailz/discordjv/action/guild/members/RequestGuildMembersAction.java
  src/main/java/com/seailz/discordjv/gateway/GatewayFactory.java
  src/main/java/com/seailz/discordjv/gateway/events/DispatchedEvents.java
  src/main/java/com/seailz/discordjv/model/application/Intent.java
  src/main/java/com/seailz/discordjv/model/guild/Guild.java
  src/main/java/com/seailz/discordjv/utils/TriFunction.java
  src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java
Labels: type: feature, priority: low, status: completed, status: claimed

#114 [FEATURE] Guild Bans -> Guild Moderation Intent
  src/main/java/com/seailz/discordjv/model/application/Intent.java
Labels: type: feature, priority: low, status: completed

#116 Update pom.xml
  pom.xml
Labels: type: bug, priority: low, dependencies, status: completed

#77 [FEATURE] Linked Roles
  README.md
  pom.xml
  src/main/java/com/seailz/discordjv/DiscordJv.java
  src/main/java/com/seailz/discordjv/gateway/GatewayFactory.java
  src/main/java/com/seailz/discordjv/gateway/heartbeat/HeartbeatCycle.java
  src/main/java/com/seailz/discordjv/linked/LinkedRoles.java
  src/main/java/com/seailz/discordjv/linked/LinkedRolesRestController.java
  src/main/java/com/seailz/discordjv/linked/application.properties
  src/main/java/com/seailz/discordjv/linked/package-info.java
  src/main/java/com/seailz/discordjv/linked/response/Response.java
  src/main/java/com/seailz/discordjv/linked/response/error/CodeNotPresentResponse.java
  src/main/java/com/seailz/discordjv/linked/response/error/InvalidEndpointResponse.java
  src/main/java/com/seailz/discordjv/model/application/Application.java
  src/main/java/com/seailz/discordjv/model/application/ApplicationRoleConnectionMetadata.java
  src/main/java/com/seailz/discordjv/model/guild/Guild.java
  src/main/java/com/seailz/discordjv/utils/Checker.java
  src/main/java/com/seailz/discordjv/utils/URLS.java
  src/main/java/com/seailz/discordjv/utils/cache/Cache.java
  src/main/java/com/seailz/discordjv/utils/discordapi/DiscordRequest.java
  src/main/java/com/seailz/discordjv/utils/discordapi/RequestQueueHandler.java
Labels: status: in progress, type: feature, priority: medium, status: claimed, type: examples

#117 [FEATURE] Guild Member Flags
  src/main/java/com/seailz/discordjv/model/guild/Member.java
  src/main/java/com/seailz/discordjv/model/guild/MemberFlags.java
Labels: type: feature, priority: low, status: completed

#119 [FEATURE] Command customization
  src/main/java/com/seailz/discordjv/DiscordJv.java
  src/main/java/com/seailz/discordjv/command/Command.java
  src/main/java/com/seailz/discordjv/command/annotation/ContextCommandInfo.java
  src/main/java/com/seailz/discordjv/command/annotation/Locale.java
  src/main/java/com/seailz/discordjv/command/annotation/SlashCommandInfo.java
Labels: type: feature, priority: medium, status: completed
