Repository discord-jar/discord.jar, pull requests merged in 2023-05, with the labels that each got.

#165 [FEATURE] Member Caching
  src/main/java/com/seailz/discordjar/DiscordJar.java
  src/main/java/com/seailz/discordjar/DiscordJarBuilder.java
  src/main/java/com/seailz/discordjar/cache/Cache.java
  src/main/java/com/seailz/discordjar/gateway/events/DispatchedEvents.java
  src/main/java/com/seailz/discordjar/model/guild/Guild.java
Labels: type: feature, priority: medium, status: completed

#171 feat(builder): Added a builder class to discord.jar
  README.md
  src/main/java/com/seailz/discordjar/DiscordJar.java
  src/main/java/com/seailz/discordjar/DiscordJarBuilder.java
Labels: type: feature, priority: medium, status: completed, type: doc

#172 feat(messages, permissions): added necessary additions for voice messages
  src/main/java/com/seailz/discordjar/action/message/MessageCreateAction.java
  src/main/java/com/seailz/discordjar/action/message/MessageEditAction.java
  src/main/java/com/seailz/discordjar/model/message/Message.java
  src/main/java/com/seailz/discordjar/model/message/MessageFlag.java
  src/main/java/com/seailz/discordjar/utils/permission/Permission.java
Labels: type: feature, priority: medium, status: completed, type: enhancement

#94 [FEATURE] Guild Methods
  examples/Bot.java
  src/main/java/com/seailz/discordjar/model/guild/Guild.java
  src/main/java/com/seailz/discordjar/model/guild/GuildBan.java
  src/main/java/com/seailz/discordjar/model/guild/GuildIntegration.java
  src/main/java/com/seailz/discordjar/utils/Checker.java
  src/main/java/com/seailz/discordjar/utils/URLS.java
  src/main/java/examples/Bot.java
  src/main/java/examples/ExampleCommand.java
  src/main/java/examples/ExampleMessageCommand.java
Labels: status: in progress, type: feature, priority: high, LARGE, IMPORTANT

#173 feat(gateway): added support for sharding
  src/main/java/com/seailz/discordjar/DiscordJar.java
  src/main/java/com/seailz/discordjar/DiscordJarBuilder.java
  src/main/java/com/seailz/discordjar/gateway/GatewayFactory.java
  src/main/java/com/seailz/discordjar/utils/URLS.java
  src/main/java/com/seailz/discordjar/utils/rest/DiscordRequest.java
Labels: type: feature, priority: low, status: completed

#177 feat(urls): implemented api release customization
  src/main/java/com/seailz/discordjar/DiscordJar.java
  src/main/java/com/seailz/discordjar/DiscordJarBuilder.java
  src/main/java/com/seailz/discordjar/model/api/APIRelease.java
  src/main/java/com/seailz/discordjar/model/api/version/APIVersion.java
  src/main/java/com/seailz/discordjar/model/api/version/APIVersionState.java
  src/main/java/com/seailz/discordjar/utils/HTTPOnlyInfo.java
  src/main/java/com/seailz/discordjar/utils/URLS.java
Labels: type: feature, priority: low, status: completed

#178 feat(transcripts): implemented a feature that returns all attachments
  src/main/java/com/seailz/discordjar/model/channel/interfaces/Transcriptable.java
Labels: priority: low, status: completed, type: enhancement
